language: R
cache: packages
latex: false
sudo: required
dist: trusty

r:
  - release

# Add GDAL, GEOS, proj, and units2 dependencies.
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# Binary versions of packages to reduce build time.
r_binary_packages:
  - dplyr
  - leaflet
  - markdown
  - readr
  - rmarkdown
  - rgdal
  - sp
  - sf
  - stringi
  - tidyr
  - ggplot2
  - geojsonsf
  - httr
  - rlang
  - jsonlite
  - digest
