language: R
cache: packages
latex: false
sudo: required
os: linux
dist: bionic

r:
  - release

# Add GDAL, GEOS, proj, and units2 dependencies.
#before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
#  - sudo apt-get --yes --force-yes update -qq
#  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

#services:
#  - docker

before_install:
#  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

r_packages:
  - sp
  - rgdal
  - rgeos
  - sf
  - dplyr
  - leaflet
  - markdown
  - readr
  - rmarkdown
  - stringi
  - tidyr
  - ggplot2
  - geojsonsf
  - httr
  - rlang
  - jsonlite
  - digest
